imports:
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/assets.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/fos_ck_editor.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_flysystem.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_uploader.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_doctrine_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yaml" }
## Uncomment to enable webauthn
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/webauthn.yaml" }


framework:
    translator: { fallbacks: ['%env(LOCALE)%'] }

lexik_translation:
    fallback_locale:  '%env(LOCALE)%'      # (required) default locale to use
    managed_locales: [ 'de', 'fr', 'it', 'en'] # !IMPORTANT: Change to strings and not environment variables
    resources_registration:
        type:                 all  # all | files | database
        managed_locales_only: false # set to true to only include managed_locales

networking_init_cms:
## Uncomment to enable webauthn
    webauthn:
        enabled: true
    google_authenticator:
        enabled: false
        server: 'sandbox-6.test'
        trusted_ip_list:
            - 127.0.8.1
        forced_for_role:
            - ROLE_SONATA_ADMIN
            - ROLE_SUPER_ADMIN
    single_language: false
    allow_locale_cookie: true
    class:
        page: "App\\Entity\\Page"
        user: "App\\Entity\\User"
    languages:
        - { label: D, locale: de }
        - { label: F, locale: fr }
        - { label: I, locale: it }
        - { label: E, locale: en }
    # Bootstrap some template settings to get you started
    templates:
        'app_single_column':
            template: "page/one_column.html.twig"
            name: "Single Column"
            icon: "bundles/networkinginitcms/img/template_header_one_column.png"
            zones:
                - { name: header, class: 'col-md-12' }
                - { name: main_content, class: 'col-md-12'}
        'app_two_column':
            template: "page/two_column.html.twig"
            name: "Two Column"
            icon: "bundles/networkinginitcms/img/template_header_two_column.png"
            zones:
                - { name: header , class: 'col-md-12'}
                - { name: left , class: 'col-md-3', max_content_items: 1, restricted_types: ['Networking\InitCmsBundle\Entity\Text'] }
                - { name: right , class: 'col-md-9'}
                - { name: footer , class: 'col-md-12'}
    cache:
        activate: true #enable for product, false in dev config
    content_types:
        -
            name: "Text"
            class: 'Networking\InitCmsBundle\Entity\Text'
            icon: 'ki-outline ki-text-align-left'
            default_template: '@NetworkingInitCms/Text/frontend_text_block.html.twig'
        -
            name: "Gallery"
            class: 'Networking\InitCmsBundle\Entity\GalleryView'
            icon: 'ki-outline ki-picture'
            default_template: '@NetworkingInitCms/GalleryView/gallery_view.html.twig'
        -
            name: 'form_generator'
            class: 'Networking\FormGeneratorBundle\Model\FormPageContent'
            icon: 'ki-outline ki-questionnaire-tablet'
            default_template: '@NetworkingFormGenerator/Form/form_page_content.html.twig'


when@dev:
    networking_init_cms:
        cache:
            activate: false