networking_init_cms:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/routing.yaml"
    prefix:   /

networking_elsticsearch:
    resource: "@NetworkingElasticSearchBundle/Resources/config/routing.yaml"
    prefix:   /

networking_api_forms:
    type: attribute
    prefix: /admin/cms/forms/api
    resource: Networking\FormGeneratorBundle\Controller\FormAdminController

networking_form_view:
    path: /view_form/{id}
    defaults: { _controller: 'Networking\FormGeneratorBundle\Controller\FrontendFormController::viewFormAction'}
