networking_init_cms:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/routing.yaml"
    prefix:   /

networking_elsticsearch:
    resource: "@NetworkingElasticSearchBundle/Resources/config/routing.yaml"
    prefix:   /

networking_form_generator:
    resource: "@NetworkingFormGeneratorBundle/Resources/config/routing.yaml"
    prefix:   /
    schemes:  [https]

## Comment out to disable webauthn
networking_init_cms_webauthn:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/webauthn.yaml"
    prefix:   /

