# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $rootDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Networking\InitCmsBundle\Menu\FrontendMenuBuilder:
        arguments:
            $allowLocaleCookie: '%networking_init_cms.allow_locale_cookie%'

    # Create the left main menu and right main menu for the frontend
    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ['@Networking\InitCmsBundle\Menu\FrontendMenuBuilder', 'buildMenu']
        arguments: [menu_name: 'Main menu', 'navbar-nav me-auto mb-2 mb-lg-0' ]
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    app.menu.lang:
        class: Knp\Menu\MenuItem
        factory: ['@Networking\InitCmsBundle\Menu\FrontendMenuBuilder', 'createLangMenu']
        arguments: [ '@request_stack', '%networking_init_cms.page.languages%', 'dropdown-menu' ]
        tags:
            - { name: knp_menu.menu, alias: langMenu }

    app.menu.frontend_footer_menu:
        class: Knp\Menu\MenuItem
        factory: ['@Networking\InitCmsBundle\Menu\FrontendMenuBuilder', 'buildMenu']
        arguments: [ 'Footer-Navigation', '']
        tags:
            - { name: knp_menu.menu, alias: footerMenu }

    Sonata\UserBundle\Model\UserManagerInterface:
        alias: networking_init_cms.user_manager

